language: node_js
node_js:
  - iojs
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install
env:
  global:
    secure: lyiH95VSZVpAKpVEi5Szjn1sv3FekrIeJQ1r4HliRkorDdKPw4ai66Qzzzbfvu2TffBCFwaa04mBhl7rNYT6qlt5U7XFIAoIkyT1jAJxQ1WxN4swd5bGyqDFCQb7mAUM6S5gu1OwM+53WKCC3nebyNGZo+XP6tvxkE9CTHHRLCc=
